/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as ArtAtlasRouteImport } from './routes/art-atlas'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LanguageLabRouteImport } from './routes/language-lab'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LiteraturePortalRouteImport } from './routes/literature-portal'
import { Route as MusicArchiveRouteImport } from './routes/music-archive'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ProvenanceRouteImport } from './routes/provenance'
import { Route as SourcesExplorerRouteImport } from './routes/sources-explorer'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArtRouteImport } from './routes/art'
import { Route as AuthorsRouteImport } from './routes/authors'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as LiteratureRouteImport } from './routes/literature'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MusicRouteImport } from './routes/music'
import { Route as ProverbsRouteImport } from './routes/proverbs'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ApiArchiveRouteImport } from './routes/api/archive'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiArchiveTypeRouteImport } from './routes/api/archive.$type'
import { Route as ArchiveTypeSlugRouteImport } from './routes/archive/$type.$slug'
import { Route as ApiRecordsTypeSlugRouteImport } from './routes/api/records.$type.$slug'

const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtAtlasRoute = ArtAtlasRouteImport.update({
  id: '/art-atlas',
  path: '/art-atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageLabRoute = LanguageLabRouteImport.update({
  id: '/language-lab',
  path: '/language-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteraturePortalRoute = LiteraturePortalRouteImport.update({
  id: '/literature-portal',
  path: '/literature-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicArchiveRoute = MusicArchiveRouteImport.update({
  id: '/music-archive',
  path: '/music-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvenanceRoute = ProvenanceRouteImport.update({
  id: '/provenance',
  path: '/provenance',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesExplorerRoute = SourcesExplorerRouteImport.update({
  id: '/sources-explorer',
  path: '/sources-explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtRoute = ArtRouteImport.update({
  id: '/art',
  path: '/art',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsRoute = AuthorsRouteImport.update({
  id: '/authors',
  path: '/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const LiteratureRoute = LiteratureRouteImport.update({
  id: '/literature',
  path: '/literature',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const ProverbsRoute = ProverbsRouteImport.update({
  id: '/proverbs',
  path: '/proverbs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveRoute = ApiArchiveRouteImport.update({
  id: '/api/archive',
  path: '/api/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveTypeRoute = ApiArchiveTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => ApiArchiveRoute,
} as any)
const ArchiveTypeSlugRoute = ArchiveTypeSlugRouteImport.update({
  id: '/archive/$type/$slug',
  path: '/archive/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecordsTypeSlugRoute = ApiRecordsTypeSlugRouteImport.update({
  id: '/api/records/$type/$slug',
  path: '/api/records/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/atlas': typeof AtlasRoute
  '/art-atlas': typeof ArtAtlasRoute
  '/explore': typeof ExploreRoute
  '/language-lab': typeof LanguageLabRoute
  '/learn': typeof LearnRoute
  '/literature-portal': typeof LiteraturePortalRoute
  '/music-archive': typeof MusicArchiveRoute
  '/people': typeof PeopleRoute
  '/provenance': typeof ProvenanceRoute
  '/sources-explorer': typeof SourcesExplorerRoute
  '/stats': typeof StatsRoute
  '/timeline': typeof TimelineRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/art': typeof ArtRoute
  '/authors': typeof AuthorsRoute
  '/graph': typeof GraphRoute
  '/heritage': typeof HeritageRoute
  '/language': typeof LanguageRoute
  '/literature': typeof LiteratureRoute
  '/media': typeof MediaRoute
  '/music': typeof MusicRoute
  '/proverbs': typeof ProverbsRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/api/archive': typeof ApiArchiveRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/archive/$type': typeof ApiArchiveTypeRoute
  '/archive/$type/$slug': typeof ArchiveTypeSlugRoute
  '/api/records/$type/$slug': typeof ApiRecordsTypeSlugRoute
}
export interface FileRoutesByTo {
  '/atlas': typeof AtlasRoute
  '/art-atlas': typeof ArtAtlasRoute
  '/explore': typeof ExploreRoute
  '/language-lab': typeof LanguageLabRoute
  '/learn': typeof LearnRoute
  '/literature-portal': typeof LiteraturePortalRoute
  '/music-archive': typeof MusicArchiveRoute
  '/people': typeof PeopleRoute
  '/provenance': typeof ProvenanceRoute
  '/sources-explorer': typeof SourcesExplorerRoute
  '/stats': typeof StatsRoute
  '/timeline': typeof TimelineRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/art': typeof ArtRoute
  '/authors': typeof AuthorsRoute
  '/graph': typeof GraphRoute
  '/heritage': typeof HeritageRoute
  '/language': typeof LanguageRoute
  '/literature': typeof LiteratureRoute
  '/media': typeof MediaRoute
  '/music': typeof MusicRoute
  '/proverbs': typeof ProverbsRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/api/archive': typeof ApiArchiveRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/archive/$type': typeof ApiArchiveTypeRoute
  '/archive/$type/$slug': typeof ArchiveTypeSlugRoute
  '/api/records/$type/$slug': typeof ApiRecordsTypeSlugRoute
}
export interface FileRoutesById {
  '/atlas': typeof AtlasRoute
  '/art-atlas': typeof ArtAtlasRoute
  '/explore': typeof ExploreRoute
  '/language-lab': typeof LanguageLabRoute
  '/learn': typeof LearnRoute
  '/literature-portal': typeof LiteraturePortalRoute
  '/music-archive': typeof MusicArchiveRoute
  '/people': typeof PeopleRoute
  '/provenance': typeof ProvenanceRoute
  '/sources-explorer': typeof SourcesExplorerRoute
  '/stats': typeof StatsRoute
  '/timeline': typeof TimelineRoute
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/art': typeof ArtRoute
  '/authors': typeof AuthorsRoute
  '/graph': typeof GraphRoute
  '/heritage': typeof HeritageRoute
  '/language': typeof LanguageRoute
  '/literature': typeof LiteratureRoute
  '/media': typeof MediaRoute
  '/music': typeof MusicRoute
  '/proverbs': typeof ProverbsRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/sources': typeof SourcesRoute
  '/api/archive': typeof ApiArchiveRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/api/archive/$type': typeof ApiArchiveTypeRoute
  '/archive/$type/$slug': typeof ArchiveTypeSlugRoute
  '/api/records/$type/$slug': typeof ApiRecordsTypeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/atlas'
    | '/art-atlas'
    | '/explore'
    | '/language-lab'
    | '/learn'
    | '/literature-portal'
    | '/music-archive'
    | '/people'
    | '/provenance'
    | '/sources-explorer'
    | '/stats'
    | '/timeline'
    | '/'
    | '/about'
    | '/art'
    | '/authors'
    | '/graph'
    | '/heritage'
    | '/language'
    | '/literature'
    | '/media'
    | '/music'
    | '/proverbs'
    | '/research'
    | '/search'
    | '/sources'
    | '/api/archive'
    | '/api/search'
    | '/api/archive/$type'
    | '/archive/$type/$slug'
    | '/api/records/$type/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/atlas'
    | '/art-atlas'
    | '/explore'
    | '/language-lab'
    | '/learn'
    | '/literature-portal'
    | '/music-archive'
    | '/people'
    | '/provenance'
    | '/sources-explorer'
    | '/stats'
    | '/timeline'
    | '/'
    | '/about'
    | '/art'
    | '/authors'
    | '/graph'
    | '/heritage'
    | '/language'
    | '/literature'
    | '/media'
    | '/music'
    | '/proverbs'
    | '/research'
    | '/search'
    | '/sources'
    | '/api/archive'
    | '/api/search'
    | '/api/archive/$type'
    | '/archive/$type/$slug'
    | '/api/records/$type/$slug'
  id:
    | '/atlas'
    | '/art-atlas'
    | '/explore'
    | '/language-lab'
    | '/learn'
    | '/literature-portal'
    | '/music-archive'
    | '/people'
    | '/provenance'
    | '/sources-explorer'
    | '/stats'
    | '/timeline'
    | '__root__'
    | '/'
    | '/about'
    | '/art'
    | '/authors'
    | '/graph'
    | '/heritage'
    | '/language'
    | '/literature'
    | '/media'
    | '/music'
    | '/proverbs'
    | '/research'
    | '/search'
    | '/sources'
    | '/api/archive'
    | '/api/search'
    | '/api/archive/$type'
    | '/archive/$type/$slug'
    | '/api/records/$type/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AtlasRoute: typeof AtlasRoute
  ArtAtlasRoute: typeof ArtAtlasRoute
  ExploreRoute: typeof ExploreRoute
  LanguageLabRoute: typeof LanguageLabRoute
  LearnRoute: typeof LearnRoute
  LiteraturePortalRoute: typeof LiteraturePortalRoute
  MusicArchiveRoute: typeof MusicArchiveRoute
  PeopleRoute: typeof PeopleRoute
  ProvenanceRoute: typeof ProvenanceRoute
  SourcesExplorerRoute: typeof SourcesExplorerRoute
  StatsRoute: typeof StatsRoute
  TimelineRoute: typeof TimelineRoute
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArtRoute: typeof ArtRoute
  AuthorsRoute: typeof AuthorsRoute
  GraphRoute: typeof GraphRoute
  HeritageRoute: typeof HeritageRoute
  LanguageRoute: typeof LanguageRoute
  LiteratureRoute: typeof LiteratureRoute
  MediaRoute: typeof MediaRoute
  MusicRoute: typeof MusicRoute
  ProverbsRoute: typeof ProverbsRoute
  ResearchRoute: typeof ResearchRoute
  SearchRoute: typeof SearchRoute
  SourcesRoute: typeof SourcesRoute
  ApiArchiveRoute: typeof ApiArchiveRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  ArchiveTypeSlugRoute: typeof ArchiveTypeSlugRoute
  ApiRecordsTypeSlugRoute: typeof ApiRecordsTypeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art-atlas': {
      id: '/art-atlas'
      path: '/art-atlas'
      fullPath: '/art-atlas'
      preLoaderRoute: typeof ArtAtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language-lab': {
      id: '/language-lab'
      path: '/language-lab'
      fullPath: '/language-lab'
      preLoaderRoute: typeof LanguageLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literature-portal': {
      id: '/literature-portal'
      path: '/literature-portal'
      fullPath: '/literature-portal'
      preLoaderRoute: typeof LiteraturePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-archive': {
      id: '/music-archive'
      path: '/music-archive'
      fullPath: '/music-archive'
      preLoaderRoute: typeof MusicArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provenance': {
      id: '/provenance'
      path: '/provenance'
      fullPath: '/provenance'
      preLoaderRoute: typeof ProvenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources-explorer': {
      id: '/sources-explorer'
      path: '/sources-explorer'
      fullPath: '/sources-explorer'
      preLoaderRoute: typeof SourcesExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art': {
      id: '/art'
      path: '/art'
      fullPath: '/art'
      preLoaderRoute: typeof ArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors': {
      id: '/authors'
      path: '/authors'
      fullPath: '/authors'
      preLoaderRoute: typeof AuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/literature': {
      id: '/literature'
      path: '/literature'
      fullPath: '/literature'
      preLoaderRoute: typeof LiteratureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proverbs': {
      id: '/proverbs'
      path: '/proverbs'
      fullPath: '/proverbs'
      preLoaderRoute: typeof ProverbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive': {
      id: '/api/archive'
      path: '/api/archive'
      fullPath: '/api/archive'
      preLoaderRoute: typeof ApiArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive/$type': {
      id: '/api/archive/$type'
      path: '/$type'
      fullPath: '/api/archive/$type'
      preLoaderRoute: typeof ApiArchiveTypeRouteImport
      parentRoute: typeof ApiArchiveRoute
    }
    '/archive/$type/$slug': {
      id: '/archive/$type/$slug'
      path: '/archive/$type/$slug'
      fullPath: '/archive/$type/$slug'
      preLoaderRoute: typeof ArchiveTypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/records/$type/$slug': {
      id: '/api/records/$type/$slug'
      path: '/api/records/$type/$slug'
      fullPath: '/api/records/$type/$slug'
      preLoaderRoute: typeof ApiRecordsTypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiArchiveRouteChildren {
  ApiArchiveTypeRoute: typeof ApiArchiveTypeRoute
}

const ApiArchiveRouteChildren: ApiArchiveRouteChildren = {
  ApiArchiveTypeRoute: ApiArchiveTypeRoute,
}

const ApiArchiveRouteWithChildren = ApiArchiveRoute._addFileChildren(
  ApiArchiveRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AtlasRoute: AtlasRoute
  ArtAtlasRoute: ArtAtlasRoute
  ExploreRoute: ExploreRoute
  LanguageLabRoute: LanguageLabRoute
  LearnRoute: LearnRoute
  LiteraturePortalRoute: LiteraturePortalRoute
  MusicArchiveRoute: MusicArchiveRoute
  PeopleRoute: PeopleRoute
  ProvenanceRoute: ProvenanceRoute
  SourcesExplorerRoute: SourcesExplorerRoute
  StatsRoute: StatsRoute
  TimelineRoute: TimelineRoute
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArtRoute: ArtRoute,
  AuthorsRoute: AuthorsRoute,
  GraphRoute: GraphRoute,
  HeritageRoute: HeritageRoute,
  LanguageRoute: LanguageRoute,
  LiteratureRoute: LiteratureRoute,
  MediaRoute: MediaRoute,
  MusicRoute: MusicRoute,
  ProverbsRoute: ProverbsRoute,
  ResearchRoute: ResearchRoute,
  SearchRoute: SearchRoute,
  SourcesRoute: SourcesRoute,
  ApiArchiveRoute: ApiArchiveRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  ArchiveTypeSlugRoute: ArchiveTypeSlugRoute,
  ApiRecordsTypeSlugRoute: ApiRecordsTypeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
